name = "titan-vault-api"
main = "src/index.ts"
compatibility_date = "2024-03-27"

[[r2_buckets]]
binding = "R2"
bucket_name = "titan-vault"

[[routes]]
pattern = "https://api.titanvaultencrypt.com/api/*"
zone_name = "titanvaultencrypt.com"

[vars]
COGNITO_REGION = "us-east-1"
COGNITO_USER_POOL_ID = "us-east-1_ZSdwAA8FJ"
COGNITO_CLIENT_ID = "28bk3ok0246oodeorj8l5ikk6c"
